[package]
name = "shared"
version = "1.0.0"

[dependencies]
bson = "0.12.2"
mongodb = "0.3.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4.4"
chrono = { version = "0.4", features = ["serde"] }
rocket = "0.3.15"
